### ISSUE TITLE
BicUtil#validate trasnlates BicFormatException with specific violation to UNKNOWN

### ISSUE THREAD

**Issue by achrzastowski-pinecone** [arturmkrtchyan/iban4j#104]
The problem is this line: 

https://github.com/arturmkrtchyan/iban4j/blob/master/src/main/java/org/iban4j/BicUtil.java#L59

when there is a BicFormatException with specified violation, exception handling translates it to UNKNOWN. It would be good to do not translate BicFormatException then it is possible to preapare custom validation messages etc. rather than using exception message  to user. 
Change is really simple: 

```
.....
        } catch (UnsupportedCountryException | BicFormatException e) {
            throw e;
        } catch (RuntimeException e) {
            throw new BicFormatException(UNKNOWN, e.getMessage());
        }
.....
```

**Comment by hajk1** [comment]
will be merged in next release
