### ISSUE TITLE
French National check digits is wrong

### ISSUE THREAD

**Issue by LiamReynaud** [arturmkrtchyan/iban4j#107]
Hello,

Thank you for you work.

The National check digits (for France) doesn't return the last 2 digits xx but the kk (country code)
according to the following page : https://en.wikipedia.org/wiki/International_Bank_Account_Number

**Comment by FrankHossfeld** [comment]
please look here: https://github.com/arturmkrtchyan/iban4j/issues/34

**Comment by hajk1** [comment]
duplicate #34
