### ISSUE TITLE
Minor: CountryCode.getAlpha2() returns name instead of code

### ISSUE THREAD

**Issue by salmov-e-n** [arturmkrtchyan/iban4j#115]
https://github.com/arturmkrtchyan/iban4j/blob/master/src/main/java/org/iban4j/CountryCode.java#L791

**Comment by hajk1** [comment]
This is a bit confusing, "name()" method is an internal method of Enum and the return value is correct(Alpha2). 
However, it is very hard to distinguish between "name" and "name()".
I might refactor the "name" variable to something more meaningful like "Description" to avoid this confusion.

**Comment by salmov-e-n** [comment]
Thanks, agree! It was just a confusion. I'm not sure variable needs to be refactored.
