### ISSUE TITLE
Violation overriden to UNKNOWN in BicUtil & IbanUtil

### ISSUE THREAD

**Issue by nbrass** [arturmkrtchyan/iban4j#116]
Hi,
currently the Violation is overriden with value "UNKNOWN" in `BicUtil.validate()` & `IbanUtil.validate()` as BicFormatException & IbanFormatException are RuntimeExceptions and caught in the RuntimeException catch-Block.

Can you please fix this? Thanks in advance!

Best regards
Norman

**Comment by hajk1** [comment]
@nbrass I checked the code. It seems to need modifications. But I did not get your exact requirements. 
Do you expect a more meaningful "IbanFormatException" and "BicFormatException" in both methods?

**Comment by nbrass** [comment]
@hajk1 I would expect the violation set from the root cause. From my point of view you need to check if the RuntimeException is of type BicFormatException or IbanFormatException and in these cases rethrow it directly instead of creating a new one.

**Comment by hajk1** [comment]
It makes sense, I will fix it in the next release

**Comment by hajk1** [comment]
IbanUtil.validate had the desired feature, and Iban4jException covers both BicFormatException & IbanFormatException. The BicUtil.validate is now changed to have the same functionality.
