### ISSUE TITLE
pom.xml change URL to allowe renovate fetch release notes 

### ISSUE THREAD

**Issue by marwin1991** [arturmkrtchyan/iban4j#120]
Hello,

I have noticed that renovate cannot resolve release notes for this lib.

To do so, in `pom.xml` we have to have entry like that: 
```xml
<scm>
    <url>scm:git:https://github.com/path_to_repository</url>
</scm>
```
https://docs.renovatebot.com/modules/datasource/maven/

Do you think that we can change it?

**Comment by hajk1** [comment]
Yes, we can do it for sure.
