### ISSUE TITLE
Generate IBAN for GB with sort code and account number

### ISSUE THREAD

**Issue by fahim1D** [arturmkrtchyan/iban4j#124]
Using the example from the README:
```java
Iban iban = new Iban.Builder()
                    .countryCode(CountryCode.GB)
                    .bankCode(123456)
                    .accountNumber(12345678)
                    .build();
```
I encounter an **IbanFormatException**: `[1234] must contain only upper case letters.`

In the code above, I'm supplying [sort code](https://en.wikipedia.org/wiki/Sort_code) to the `bankCode` field. After I investigated the the **iban4j** code a little bit, I was able to get a working example by assigning the sort code to the `branchCode` field instead, and I supplied a `bankCode` consisting only of letters.
```java
Iban iban = new Iban.Builder()
                    .countryCode(CountryCode.GB)
                    .bankCode("ABCD")
                    .branchCode(123456)
                    .accountNumber(12345678)
                    .build();
```
I was able to get a bank code using https://www.iban.com/calculate-iban, which only requires a sort code and account number.

Can **iban4j** calculate IBANs from just sort code and account number? The website was just to test the results of this library, but in production I won't have access to a `bankCode` property.

Note: I supplied a dummy bank code and account number but I believe the point still stands.

**Comment by hajk1** [comment]
AFAIK in the UK, the sort code is used to identify the bank and the branch where an account is held. Each bank has a unique set of sort codes for its various branches. If you have the sort code, you can often determine the bank and its specific branch.

There are several methods to find out a bank branch using its sort code:

1. Bank's Official Website or Mobile Application
2. Online Directories
3. Contacting the Bank Directly
4. Using API Services

Iban4j is an offline library and tries to be generic for all the supporting countries. It's so tricky to try to keep up-to-date details that are country-specific and volatile. Maybe it's better to provide some online services in the future which are hardly possible to be free of charge.

@fahim1D  Please confirm if I understood your desired requirement
