### ISSUE TITLE
Add Burundi (ISO 13616)

### ISSUE THREAD

**Issue by abadev2024** [arturmkrtchyan/iban4j#140]
Could you please add Burundi to the supported countries? It is oficially listed by ISO 13616.
Thank you in advance.

The following code snippets could be helpful. 

structures.put(CountryCode.BI,
                new BbanStructure(
                        BbanStructureEntry.bankCode(5, 'n'),
                        BbanStructureEntry.branchCode(5, 'n'),
                        BbanStructureEntry.accountNumber(13, 'n')));

{new Iban.Builder()
                        .countryCode(CountryCode.BI)
                        .bankCode("10000")
                        .branchCode("10001")
                        .accountNumber("0000332045181")
                        .build(), "BI4210000100010000332045181"},

**Comment by hajk1** [comment]
@abadev2024 Yes, I will fix it for the next release.
