### ISSUE TITLE
Public API for bank and branch code checks

### ISSUE THREAD

**Issue by PabloLec** [arturmkrtchyan/iban4j#155]
Hello,

I have a use case where I need to validate a bank code and branch code for a specific country. Specifically, I need to ensure that the bank code has the correct length and valid characters for the given country. The same applies to the branch code, however, since it's not mandatory for all countries, I also need to determine if its presence is legitimate or not.

Currently, some potentially helpful methods, like `validateBbanEntries` in `IbanUtil`, are private. I would like to propose making this functionality public and more user-friendly. For example, a static method that takes a `CountryCode`, a `BbanEntryType`, and a string value as arguments. To remain consistent with the rest of the API, this method would return void and throw an exception if validation fails.
Beyond the bank code and branch code, this logic could likely be easily extended to all entries of `BbanEntryType`.

I’d like to know if you’re open to this idea, as I believe this use case isn’t uncommon. In practice, I have a part of an IBAN isolated, and I need to validate it without constructing a full `Iban` object.

I’m happy to provide a proper implementation for this, but I want to ensure that my proposal aligns with your vision for the library first.

I think these new static methods would fit well within `BbanStructure`. This would also involve moving some logic from `IbanUtil` (e.g., `validateBbanEntryCharacterType`) to `BbanStructure`.

**Comment by hajk1** [comment]
Hello, if you’re ready to proceed with a clean and efficient implementation, let’s move forward.

**Comment by PabloLec** [comment]
@hajk1 Hi, I just submitted the corresponding PR for #156
