### ISSUE TITLE
Iban validate error

### ISSUE THREAD

**Issue by sonmezburak** [arturmkrtchyan/iban4j#17]
Hi ,
TR010012300882101517977799
Calculatechechdigit error.
Help me :)

**Comment by arturmkrtchyan** [comment]
Hi @sonmezburak 

Check digits can be from 02-98 (00 and 01 are not possible). 

The ECBS document replicates part of the ISO/IEC 7064:2003 standard as a method for generating check digits in the range 02 to 98.

**Comment by sonmezburak** [comment]
Hi Artur,
I need earlier this week. 
I would be glad to help if

**Comment by sonmezburak** [comment]
Hi Artur,

Generating IBAN check digits: 

According to the ECBS "generation of the IBAN shall be the exclusive responsibility of the bank/branch servicing the account".[8] The ECBS document replicates part of the ISO/IEC 7064:2003 standard as a method for generating check digits in the range 02 to 98. Check digits in the ranges 00 to 96, 01 to 97, and 03 to 99 will also provide validation of an IBAN, but the standard is silent as to whether or not these ranges may be used.

**Comment by arturmkrtchyan** [comment]
I will change my validation to validate the use cases when the ranges are  00 to 96, 01 to 97, and 03 to 99.  But the library will not generate iban's outside of the 02-98 range. Is this enough for your use case ?

**Comment by sonmezburak** [comment]
Yes enough.

**Comment by arturmkrtchyan** [comment]
btw which version are you using ?  are you fine migrating to iban4j-3.0.1 ?

**Comment by sonmezburak** [comment]
When ready version ?

**Comment by arturmkrtchyan** [comment]
Fixed check out version 3.0.1  soon will be available in maven central

**Comment by arturmkrtchyan** [comment]
@sonmezburak  checkout 3.0.2 and let me know if it fixes your issue.

**Comment by arturmkrtchyan** [comment]
@sonmezburak I'm assuming it works now for you. Otherwise reopen the ticket.

**Comment by sonmezburak** [comment]
Thanks Artur.
