### ISSUE TITLE
iban4j.org is down

### ISSUE THREAD

**Issue by Haroenv** [arturmkrtchyan/iban4j#19]
http://iban4j.org isn't reachable

**Comment by arturmkrtchyan** [comment]
@Haroenv I was too lazy to setup a webpage for http://iban4j.org

**Comment by arturmkrtchyan** [comment]
@Haroenv I'm too lazy to to setup a web page. README has a decent documentation.

**Comment by Haroenv** [comment]
no problem, I guess the best solution is to remove the link in the description then

**Comment by marcolopes** [comment]
Link is still there... Broken!

**Comment by FrankHossfeld** [comment]
... due to missing contributor ... I think. But I agree with @arturmkrtchyan. The README is pretty good. So, at least, someone should remove the link.

**Comment by hajk1** [comment]
iban4j.org is back live now
