### ISSUE TITLE
How to handle IBANs which country codes are not supported by BbanStructure

### ISSUE THREAD

**Issue by xsveda** [arturmkrtchyan/iban4j#20]
Hi, BbanStructure structure contains description of about 65 IBANs by their country code. But how to handle IBANs for other countries?
- Is there a reason why not all of them are listed?
- Is it possible to add missing descriptions?
- Is it possible to handle such IBAN a different way using this library? 

My current problem comes from Greenland: **GL8964710001000206**

Thank you in advance for any hint!

**Comment by arturmkrtchyan** [comment]
Hi @xsveda,

Thanks for your contribution. The library contains ibans that are in IBAN registry. Anyway fill free to add new ibans if you need.

I'm in vacation currently. Will merge your pull request in 2 weeks.

**Comment by arturmkrtchyan** [comment]
@xsveda, just released a new version, check it out!

**Comment by xsveda** [comment]
Works well, thanks!
