### ISSUE TITLE
Add support for Partial IBAN Countries

### ISSUE THREAD

**Issue by Ebalaitung** [arturmkrtchyan/iban4j#24]
Currently library works straight according to ISO spec., but there is a list of countries with partially support IBAN system and have valid IBAN codes. More over many banks (like RBC etc.) work with such countries.

For more info about this countries please refer to https://www.iban.com/structure.html
I expect to have such support in this nice library.

**Comment by arturmkrtchyan** [comment]
@Ebalaitung I will add them later this week.

**Comment by Ebalaitung** [comment]
woo hoo!!! thanks gyus!
