### ISSUE TITLE
Add Support for Spaces in IBAN

### ISSUE THREAD

**Issue by Kadrei** [arturmkrtchyan/iban4j#25]
In Germany (and maybe other Countrys too) it is normal to format IBANs as such:

DE68 2105 0170 0012 3456 78

(Every 4 symbols comes a Whitespace)
This should be considered valid by the Validator.

IBANs with incorrect whitespace could still be marked as invalid, so a ```replace(" ","")``` can't handle it :(.
i.e.
DE6 821 050 170 001 234 567 8
DE68 21050170 0012 3456 78

**Comment by arturmkrtchyan** [comment]
@Kadrei Iban class has a toFormattedString method which gives you back (Every 4 symbols comes a Whitespace) formatted iban as a string.

So if you need to hard verify on string matching including format you can use that method.

I'm not convinced that this library should be validating formats as well.

**Comment by Kadrei** [comment]
Hmm, that does the reverse thing of what I want. What about a Method like ```fromFormattedString()```which returns a Iban-Instance from a formatted Iban-String.

**Comment by arturmkrtchyan** [comment]
What I would do in your case might be the following: 
```java
String ibanStr = "DE68 21050170 0012 3456 78";
String ibanStrWithoutSpaces = ibanStr.replace(" ", "");
Iban iban = Iban.valueOf(ibanStrWithoutSpaces);
boolean isIbanInRightFormat = (iban. toFormattedString() == ibanStr);
```

**Comment by hajk1** [comment]
I think it would be useful method

**Comment by Kadrei** [comment]
@arturmkrtchyan: This could be a part of a simple solution and I will use that (or something similiar). As I understand the concern regarding validation of format. But what is about a seperation of concers like the Date-API with DateFormatters? Maybe that would be a nice Addition to the Library (and it could handle more than one format). 

But I will close that issue, because I see your Point. Thanks for your time. Keep the good work up!

**Comment by arturmkrtchyan** [comment]
@Kadrei as far as I know Iban has only one format as of now (4 chars + space). One approach would be to have something like:
```java
Iban iban = Iban.valueOf("DE89 3704 0044 0532 0130 00", IbanFormat.Default);
IbanUtil.validate("AT61 1904 3002 3457 3201", IbanFormat.Default);
```

What do you think about this ?

**Comment by Kadrei** [comment]
Yeah that sounds good to me.

**Comment by arturmkrtchyan** [comment]
@Kadrei and @hajk1 new version 3.2.0 contains above-mentioned feature.
