### ISSUE TITLE
Find BIC from IBAN

### ISSUE THREAD

**Issue by umbreak** [arturmkrtchyan/iban4j#26]
Add support for finding a BIC (and bank related information) from an IBAN.

**Comment by arturmkrtchyan** [comment]
@umbreak do you have particular example in mind ? how the api could look like ?

**Comment by umbreak** [comment]
It is not clear to me at this point if it is really possible considering that some resources may be not for free. At least, [this comment](http://stackoverflow.com/questions/13135361/generate-bic-from-iban-bank-account-number#answer-17436769) suggests the reliable way requires a paying API.

**Comment by reva** [comment]
It's indeed impossible without proper reference data. You need to map between national banking identifier code and BIC (SWIFT-Code). For some countries, there may be appropriate data available (Switzerland: http://www.six-interbank-clearing.com/de/home/bank-master-data/download-bc-bank-master.html). There seem to be attempts to crawl this data from websites (https://github.com/PeterNotenboom/SwiftCodes) but I don't see how to map from IBAN to BIC given this data. Also, this data may change frequently.
