### ISSUE TITLE
Bahrain "BH72SCBLBHD18903608801"

### ISSUE THREAD

**Issue by sonmezburak** [arturmkrtchyan/iban4j#30]
Hi,
String iban = "BH72SCBLBHD18903608801";
IbanUtil.validate(iban);

return false but it has to be true.

Thanks.

**Comment by arturmkrtchyan** [comment]
@sonmezburak Fixed will release new version today evening. Thanks for reporting the issue.

**Comment by sonmezburak** [comment]
Thank you for your help

**Comment by arturmkrtchyan** [comment]
Done http://repo1.maven.org/maven2/org/iban4j/iban4j/3.2.1/
