### ISSUE TITLE
Add support for SWIFT codes

### ISSUE THREAD

**Issue by Antoniossss** [arturmkrtchyan/iban4j#32]
Hey there. Adding SWIFT validation support would be a decent complementation to this fine, light library.

**Comment by mperumalswamy** [comment]
Are there any plans to add this?

**Comment by hajk1** [comment]
Currently, we support offline BIC  code validation in the BicUtil.validate(...) method.
According to the current structure of the project, checking the existence of the BIC requires having access to an online directory or adding more than 100K BICs to the source code.
At this moment, none of them makes sense in my opinion.
