### ISSUE TITLE
Padding bank & account 

### ISSUE THREAD

**Issue by lukedirtwalker** [arturmkrtchyan/iban4j#33]
Hi,

Is there any specific reason why you do not apply any zero padding in the IbanBuilder? 
-> https://github.com/arturmkrtchyan/iban4j/blob/master/src/main/java/org/iban4j/Iban.java#L401  iterates all bban entries which have length information so if a certain value (bank or account number specifically) doesn't have the length as given in the bban entry zero padding could be applied.

Similarly the padding could be removed in IbanUtil#extractBbanEntry() (https://github.com/arturmkrtchyan/iban4j/blob/master/src/main/java/org/iban4j/IbanUtil.java#L452)

If you don't mind I would like to add such functionality, but if you have any reason against this please let me know.

Thanks

**Comment by arturmkrtchyan** [comment]
@lukedirtwalker can you share the use case where adding zero padding would be helpful to you ?

**Comment by lukedirtwalker** [comment]
Well swiss bank identifiers are from 3 to 5 digits long, so building an IBAN with the IBAN Builder in case of a bank with 3 digit identifier would require to manually add zero padding in front, however it would be more convenient if the Builder did that directly. Without this padding the IBAN would be incorrect AFAIK.
Similarly bank account numbers can have less digits than 12 so when building the IBAN we would again need to pad zeros in front.

**Comment by arturmkrtchyan** [comment]
@lukedirtwalker if it's common for all countries I would be happy to accept your help.

**Comment by kriegaex** [comment]
```
new Iban.Builder().countryCode(CountryCode.DE).bankCode("66280099").accountNumber("123456700").build()
```
```
Caught: org.iban4j.IbanFormatException: [66280099123456700] length is 17, expected BBAN length is: 18
org.iban4j.IbanFormatException: [66280099123456700] length is 17, expected BBAN length is: 18
	at org.iban4j.IbanUtil.validateBbanLength(IbanUtil.java:362)
	at org.iban4j.IbanUtil.validate(IbanUtil.java:79)
	at org.iban4j.Iban$Builder.build(Iban.java:365)
	at org.iban4j.Iban$Builder.build(Iban.java:337)
	at org.iban4j.Iban$Builder$build$2.call(Unknown Source)
```

**Comment by Dr4K4n** [comment]
This would also be useful for building danish IBANs as the lenth of the account-nr can vary

**Comment by incedo** [comment]
Also for dutch bban numbers this is needed

**Comment by kriegaex** [comment]
There is not much traction in this project. Maybe the creator is busy with his daytime job (understandable) and not maintaining it actively anymore. The last release tag here on GitHub is from May 2016.

I have long since left the project which needs this, so personally I am not concerned anymore, but anyway: The library is good otherwise, it would be nice to see this implemented. Maybe the author appreciates a pull request.

**Comment by bvaardal** [comment]
According to [Wikipedia](https://en.wikipedia.org/wiki/International_Bank_Account_Number#Basic_Bank_Account_Number):
> There is no consistency between the formats adopted.

This may be something we can add to the `BbanStructure` class. Its constructor is private, so this is backwards compatible.

I'm thinking a `BbanPaddingRule` class that can be used to indicate valid padding rules for the given country:
- Padding character
- Padding direction (left/right)
- Minimum length / maximum padding
- Applicable fields (`BbanEntryType`)

Alternative, it could be an optional part of the `BbanStructureEntry`. That would allow for more flexible padding rules, e.g. if there are different padding rules for different parts of the BBAN. With this approach, the "applicable fields" parameter goes away.

**Comment by PlexSheep** [comment]
I am facing this too.
```java
        this.iban = new Iban.Builder()
                .countryCode(CountryCode.DE)
                .bankCode("19043")
                .buildRandom();
```
```
org.iban4j.IbanFormatException: [190431468474383] length is 15, expected BBAN length is: 18
```
This is not the case if I use for example `CountryCode.AT`

**Comment by kriegaex** [comment]
@hajk1, how can this simple issue be open since 2016, if the project is still active and there have been multiple releases in the last few years? How can you so utterly ignore this?

**Comment by hajk1** [comment]
@kriegaex, sorry for the delay. I am reviewing the history of the issue to find out a good solution and release it ASAP.

**Comment by hajk1** [comment]
I added two builder methods for enabling left padding and also changing default padding characters. Currently, I am assuming "account number", "bank code" and "branch code" as target fields. However, it is very easy to extend the pattern to other bban fields if necessary.
This is going to be the pattern of using this feature:
```java
            Iban iban1 =new Iban.Builder()    
                    .leftPadding(true)
                    .countryCode(CountryCode.DE)
                    .bankCode("66280099")
                    .accountNumber("123456700")
                    .build();
            Iban iban2 = new Iban.Builder()
                    .leftPadding(true)
                    .paddingCharacter('1')
                    .countryCode(CountryCode.DE)
                    .bankCode("66280099")
                    .accountNumber("123456700")
                    .build();

```
Please let me know if it fits your requirements.

**Comment by kriegaex** [comment]
I checked out and locally built branch _Issue-33_ and tried this:

```java
import org.iban4j.CountryCode;
import org.iban4j.Iban;

class IbanPadding {
  public static void main(String[] args) {
    Iban iban = new Iban.Builder()
      .leftPadding(true)
      .countryCode(CountryCode.DE)
      .bankCode("66280099")
      .accountNumber("123456700")
      .build();
    String expected = "DE90 6628 0099 0123 4567 00";
    String actual = iban.toFormattedString();
    System.out.println("Expected: " + expected);
    System.out.println("Actual:   " + actual);
    assert expected.equals(actual);
  }
}
```

Console log:

```text
Expected: DE90 6628 0099 0123 4567 00
Actual:   DE90 6628 0099 0123 4567 00
```

The assertion also passes, i.e. after this superficial test it is looking good.

**Comment by hajk1** [comment]
@kriegaex No worries. I will update the ReadMe file and plan to release the next week.

**Comment by kriegaex** [comment]
I am actually not even working in the customer project using the library anymore. But I dislike loose ends and believe that if I open or comment on an issue, I also owe some feedback. I also like it that way in case I am a project maintainer.
