### ISSUE TITLE
Iban with 22 characters failing validation (Bulgaria and Costa Rica)

### ISSUE THREAD

**Issue by tmdomingues** [arturmkrtchyan/iban4j#42]

**Comment by pmtitou** [comment]
Same issue...

**Comment by MR-Os1** [comment]
I think this matter is fixed and needs to be closed.

**Comment by hajk1** [comment]
@MR-Os1 can you provide a sample which addresses the resolution?

**Comment by MR-Os1** [comment]
Both of the countries have BBAN Structure with 18 characters.

https://github.com/arturmkrtchyan/iban4j/blob/cf63318ec5742890705a1ea629609a6e03fad166/src/main/java/org/iban4j/bban/BbanStructure.java#L120C1-L123C69

https://github.com/arturmkrtchyan/iban4j/blob/cf63318ec5742890705a1ea629609a6e03fad166/src/main/java/org/iban4j/bban/BbanStructure.java#L107C1-L112C68

and also, the testcases contain 22 characters and all of them is passed.

https://github.com/arturmkrtchyan/iban4j/blob/cf63318ec5742890705a1ea629609a6e03fad166/src/test/java/org/iban4j/ValidIbanValidationTest.java#L40C1-L51C6

**Comment by hajk1** [comment]
Thanks for checking @MR-Os1, so I'm going to close the ticket.
