### ISSUE TITLE
Error with UK sort and account code

### ISSUE THREAD

**Issue by andyrh3** [arturmkrtchyan/iban4j#57]
Iban iban = new Iban.Builder()
                .countryCode(CountryCode.GB)
                .bankCode("090136")
                .accountNumber("99736889")
                .build();

org.iban4j.IbanFormatException: [0901] must contain only upper case letters.
	at org.iban4j.IbanUtil.validateBbanEntryCharacterType(IbanUtil.java:391)
	at org.iban4j.IbanUtil.validateBbanEntries(IbanUtil.java:379)
	at org.iban4j.IbanUtil.validate(IbanUtil.java:80)
	at org.iban4j.Iban$Builder.build(Iban.java:365)
	at org.iban4j.Iban$Builder.build(Iban.java:337)

**Comment by kc-currenxie** [comment]
same issue

**Comment by andyrh3** [comment]
Oh great thank you for looking into this I will apply the change now and see if it fixes the issue.

**Comment by fahim1D** [comment]
Sorry for necro-bumping; was this ever resolved? I passed in an all-numeric sort code for the `bankCode` property and I'm getting an `IbanFormatException` from here: https://github.com/arturmkrtchyan/iban4j/blob/master/src/main/java/org/iban4j/IbanUtil.java#L420
