### ISSUE TITLE
Wrong getAlpha2 is returned from the CountryCode

### ISSUE THREAD

**Issue by hpdrofus** [arturmkrtchyan/iban4j#60]
Hi,

In the CountryCode.java, the method getAlpha2() returns the name of the country and not the 2 letters code as it should.
Is this something that can be quickly fixed?

**Comment by bvaardal** [comment]
It returns `Enum.name()` (the name of the enum constant itself), not `CountryCode.name` or `CountryCode.getName()`.

I'm closing this issue, but feel free to reopen the issue if you actually observe incorrect behaviour.
