### ISSUE TITLE
Is this library actively developed anymore ?

### ISSUE THREAD

**Issue by goxr3plus** [arturmkrtchyan/iban4j#61]
Is this library actively developed anymore ?

**Comment by goxr3plus** [comment]
@arturmkrtchyan  Artur I forked your library and renamed to iban5j as far as i see your are not active ... ?
Can you make me a contributor on this repository so i can approve pull requests and do stuff . We will be in agreement for everything .

I am contributor to other big projects like : 
[RichTextFX](https://github.com/FXMisc/RichTextFX)
[Jave2](https://github.com/a-schild/jave2)
[XR3Player](https://github.com/goxr3plus/XR3Player)
etc

**Comment by bvaardal** [comment]
Hi @goxr3plus,

I'm working on reviving this project. Feel free to open pull requests from your fork.

**Comment by goxr3plus** [comment]
That's reaaally great news :)

**Comment by hajk1** [comment]
@goxr3plus Yes this project is active now
