### ISSUE TITLE
Vatican Iban

### ISSUE THREAD

**Issue by fiaschi** [arturmkrtchyan/iban4j#66]
Library return an error with Vatican iban.
Country Code "VA" is not present in BbanStructure.

**Comment by bvaardal** [comment]
Hi @fiaschi,

Do you have any documentation on the VA IBAN structure?

**Comment by bvaardal** [comment]
https://en.wikipedia.org/wiki/International_Bank_Account_Number#EEA_and_territories has details with https://www.iban.com/structure ("Holy See") as the source.

**Comment by mikegr** [comment]
When do you plan to release a 3.3.0?

**Comment by adnanel** [comment]
Issue still persists on 3.2.3-RELEASE.


`Iban.valueOf("VA12345678912345678912");`

Exception in thread "main" org.iban4j.UnsupportedCountryException: Country code is not supported.
	at org.iban4j.IbanUtil.validateCountryCode(IbanUtil.java:331)
	at org.iban4j.IbanUtil.validate(IbanUtil.java:74)
	at org.iban4j.Iban.valueOf(Iban.java:150)

I expected an exception like:

> [VA12345678912345678912] has invalid check digit: X, expected check digit is: Y

**Comment by FrankHossfeld** [comment]
@adnanel if you can not wait for the next release, check iban4g. Fix is included in latest release: https://github.com/NaluKit/iban4g
