### ISSUE TITLE
Iban validation fails for Belarus (BY)

### ISSUE THREAD

**Issue by desaivishal42** [arturmkrtchyan/iban4j#74]
Add Iban validation support for Belarus - BY
https://bank.codes/iban/structure/belarus/

**Comment by desaivishal42** [comment]
@arturmkrtchyan when are we releasing latest version 3.3.0?

**Comment by desaivishal42** [comment]
@bvaardal Can you release latest version please? I have checked with @arturmkrtchyan , he asked you to release. Thanks!

**Comment by FrankHossfeld** [comment]
@desaivishal42 In case the repo did not get released, you can try to use iban4g, which is based on this repo (latest commit) and was modified so that it will work with Java, GWT and J2CL. Version 2.0.0-RC3 contains the fix.

**Comment by desaivishal42** [comment]
@FrankHossfeld Great, Thank you!
I hope you will be actively maintaining that repo with upcoming bugs and fixes in iban4j repo.

**Comment by FrankHossfeld** [comment]
In case there are PRs or issues in IBAN4G, I will maintain it and create new releases.

**Comment by arturmkrtchyan** [comment]
@FrankHossfeld any interests to become a collaborator/maintainer in iban4j too ? Currently my capacity is not allowing to support the project

**Comment by hajk1** [comment]
It would be supported in the next release @desaivishal42

**Comment by desaivishal42** [comment]
Can some one release next version? @hajk1 @arturmkrtchyan @bvaardal

**Comment by hajk1** [comment]
> Can some one release next version? @hajk1 @arturmkrtchyan @bvaardal

I will do it within a week

**Comment by FrankHossfeld** [comment]
@arturmkrtchyan Thanks for offering, but, to be honest, regarding the OS projects I am already supporting, I think I will not have the time. Especially, because I would support two versions of the lib.

If you like, you can PM on Gitter. You'll find me for example in the Nalu room: https://github.com/NaluKit/nalu

**Comment by hajk1** [comment]
It's done
