### ISSUE TITLE
Adding Iban for Egypt (EG)

### ISSUE THREAD

**Issue by NaveenKumarRajulapati** [arturmkrtchyan/iban4j#88]
Currently Egypt is using `IBAN` and we don't have defined that in `CountryCode`.  Because of that we are getting `org.iban4j.UnsupportedCountryException: Country code is not supported.`

Can we just add Egypt code in the `CountryCode` class.

**Comment by NaveenKumarRajulapati** [comment]
Thanks @FrankHossfeld for your support. Let me check it.

**Comment by bogacaslan** [comment]
I created another PR for this issue, including only required changes:

https://github.com/arturmkrtchyan/iban4j/pull/103
