### ISSUE TITLE
VA Holy See fix miss in 3.2.3_RELEASE

### ISSUE THREAD

**Issue by giupaprusso** [arturmkrtchyan/iban4j#95]
The code of master branch have the fix of "VA - Holy See" IbanStructure but on maven the 3.2.3_RELEASE.jar don't have this fix. 
Please control build of branch master

**Comment by fiaschi** [comment]
Same issue here.

**Comment by FrankHossfeld** [comment]
The last release (3.2.3_RELEASE) (05-21-2021) is older than the commit "VA - Holy See" (06-04-2021).  :-) As long as no one does a new release, we will not see it in Maven Central. 

That was one reason why I forked the repo and create my own release. (https://github.com/NaluKit/iban4g) Another one is to use the lib with GWT/J2CL besides Java. Things changed/added for GWT/J2CL have no impact in a normal Java environment. The main change is the package name and that I had to add the 'gwt-regexp' dependency. If this is a problem, I could extract the the class from the project and create two new dependencies. One for GWT/J2CL and one for Java.  Everything else should be the same. (except, that I add a few fixes and PRs)

It's released at Maven Central: https://mvnrepository.com/artifact/com.github.nalukit/iban4g/2.1.0

**Comment by FrankHossfeld** [comment]
I just remove the gwt-regexp dependency.
Release 2.2.0 is on the way.

**Comment by hajk1** [comment]
Do you still have issues? @giupaprusso @fiaschi

**Comment by hajk1** [comment]
I am closing this, because no more feedback received
