### ISSUE TITLE
structureOfPLIban

### ISSUE THREAD

**Issue by mmaciekk111** [arturmkrtchyan/iban4j#98]
Hi,
now
bban > BbanStructure >
        structures.put(CountryCode.PL,
                new BbanStructure(
                        BbanStructureEntry.bankCode(**3**, 'n'),
                        BbanStructureEntry.branchCode(**4**, 'n'),
                        BbanStructureEntry.nationalCheckDigit(1, 'n'),
                        BbanStructureEntry.accountNumber(16, 'n')));

should be:
structures.put(CountryCode.PL,
                new BbanStructure(
                        BbanStructureEntry.bankCode(**4**, 'n'),
                        BbanStructureEntry.branchCode(**3**, 'n'),
                        BbanStructureEntry.nationalCheckDigit(1, 'n'),
                        BbanStructureEntry.accountNumber(16, 'n')));

Best,
M

**Comment by FrankHossfeld** [comment]
Looking at the definition [here](https://en.wikipedia.org/wiki/International_Bank_Account_Number) the definition seams correct?

```
PLkk bbbs sssx cccc cccc cccc cccc
```

```
b = National bank code
s = Branch code
x = National check digit
c = Account number
```

Can you provide more informations?

**Comment by FrankHossfeld** [comment]
Please, check this: [https://bank.codes/iban/structure/poland/](https://bank.codes/iban/structure/poland/)

I think the fourth digit - in your example - is the first digit from the branch code

**Comment by mmaciekk111** [comment]
Numer instytucji - bank code
ID oddziału - branch code.
It is in Polish, you can check on any website.




wt., 8 lis 2022, 20:03 użytkownik Frank Hossfeld ***@***.***>
napisał:

**Comment by FrankHossfeld** [comment]
Might be, but I would put my 2 pence on the international standard ...
